# Generated by Django 4.2.8 on 2023-12-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('genre', models.TextField()),
                ('description', models.TextField()),
                ('isbn', models.IntegerField()),
                ('image', models.TextField()),
                ('published', models.DateTimeField()),
                ('publisher', models.TextField()),
            ],
        ),
    ]
