# Generated by Django 4.2.8 on 2023-12-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.BigIntegerField(),
        ),
    ]
